<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Define constants -->
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="parent_link" value="chassis" />

  <xacro:property name="kinect_offset_x" value="${base_length/2}" />
  <xacro:property name="kinect_offset_z" value="0.1" />
  <xacro:property name="laser_offset_x" value="${base_length/2 + 0.01}" />
  <xacro:property name="laser_offset_z" value="0" />

  <!-- RGBD camera -->
  <link name="camera_link">
  <collision>
    <origin xyz="-0.03 0 -0.015" rpy="0 0 0"/>
    <geometry>
      <box size="0.06 0.28 0.073"/>
    </geometry>
  </collision>
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://slam_project/meshes/kinect.dae"/>
    </geometry>
  </visual>
  <inertial>
    <mass value="0.4" />
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-3" />
  </inertial>
  </link>

  <link name="camera_rgb_frame" />

  <joint name="camera_link_joint" type="fixed">
    <origin rpy="0 0 0" xyz="${kinect_offset_x} 0 ${kinect_offset_z}" />
    <parent link="${parent_link}" />
    <child link="camera_link" />
  </joint>
  <joint name="camera_rgb_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0.022 0" />
    <parent link="camera_link" />
    <child link="camera_rgb_frame" />
  </joint>
  <link name="camera_rgb_optical_frame" />
  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin rpy="${-M_PI/2} 0 ${-M_PI/2}" xyz="0 0 0" />
    <parent link="camera_rgb_frame" />
    <child link="camera_rgb_optical_frame" />
  </joint>
  <link name="camera_depth_frame" />
  <joint name="camera_depth_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0.049 0" />
    <parent link="camera_link" />
    <child link="camera_depth_frame" />
  </joint>
  <link name="camera_depth_optical_frame" />
  <joint name="camera_depth_optical_joint" type="fixed">
    <origin rpy="${-M_PI/2} 0 ${-M_PI/2}" xyz="0 0 0" />
    <parent link="camera_depth_frame" />
    <child link="camera_depth_optical_frame" />
  </joint>

  <!-- laser scanner -->
  <link name='hokuyo'>
    <pose>0 0 0 0 0 0</pose>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="1e-6" ixy="0" ixz="0"
          iyy="1e-6" iyz="0"
          izz="1e-6" />
    </inertial>
    <collision name='hokuyo_collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size=".1 .1 .1"/>
      </geometry>
    </collision>
    <visual name='hokuyo_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <mesh filename="package://slam_project/meshes/hokuyo.dae"/>
      </geometry>
    </visual>
  </link>

  <joint type="fixed" name="hokuyo_joint">
    <origin xyz="${laser_offset_x} 0 ${laser_offset_z}" rpy="0 0 0"/>
    <child link="hokuyo"/>
    <parent link="${parent_link}"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

</robot>
